package com.geomeasure.pro.data.export

import android.content.Context
import android.graphics.Bitmap
import com.geomeasure.pro.core.util.FileUtils
import com.geomeasure.pro.core.util.formatDecimals
import com.geomeasure.pro.data.local.db.entities.ProjectEntity
import com.geomeasure.pro.data.local.db.entities.VertexEntity
import com.itextpdf.text.BaseColor
import com.itextpdf.text.Chunk
import com.itextpdf.text.Document
import com.itextpdf.text.FontFactory
import com.itextpdf.text.Image
import com.itextpdf.text.Paragraph
import com.itextpdf.text.Phrase
import com.itextpdf.text.pdf.PdfPCell
import com.itextpdf.text.pdf.PdfPTable
import com.itextpdf.text.pdf.PdfWriter
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.util.Date

class PdfReportGenerator(private val context: Context) {

    fun generate(
        project: ProjectEntity,
        vertices: List<VertexEntity>,
        mapBitmap: Bitmap?
    ): File {
        val file = FileUtils.createTempFile(context, project.name, "_report.pdf")
        val document = Document()
        PdfWriter.getInstance(document, FileOutputStream(file))
        try {
            document.open()

            val titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18f, BaseColor.BLACK)
            document.add(Paragraph(project.name, titleFont))
            document.add(Paragraph("Generated by GeoMeasure Pro - ${Date(project.createdAt)}"))
            document.add(Chunk.NEWLINE)

            mapBitmap?.let {
                val stream = ByteArrayOutputStream()
                it.compress(Bitmap.CompressFormat.PNG, 90, stream)
                val image = Image.getInstance(stream.toByteArray())
                image.scaleToFit(500f, 300f)
                image.alignment = Image.ALIGN_CENTER
                document.add(image)
            }

            val summaryTable = PdfPTable(2).apply { widthPercentage = 100f }
            fun addRow(label: String, value: String) {
                summaryTable.addCell(PdfPCell(Phrase(label)).apply { backgroundColor = BaseColor(240, 240, 240) })
                summaryTable.addCell(Phrase(value))
            }
            addRow("Area", "${project.areaM2.formatDecimals(4)} m2  (${(project.areaM2 * 1e-4).formatDecimals(4)} ha)")
            addRow("Perimeter", "${project.perimeterM.formatDecimals(2)} m")
            addRow("Vertices", "${vertices.size}")
            addRow("Notes", project.notes.ifEmpty { "-" })
            document.add(summaryTable)
            document.add(Chunk.NEWLINE)

            val coordTable = PdfPTable(4).apply { widthPercentage = 100f }
            listOf("Point", "Latitude", "Longitude", "Altitude").forEach {
                coordTable.addCell(
                    PdfPCell(Phrase(it, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10f))).apply {
                        backgroundColor = BaseColor(66, 133, 244)
                    }
                )
            }
            vertices.sortedBy { it.order }.forEachIndexed { i, v ->
                coordTable.addCell("${i + 1}")
                coordTable.addCell(v.latitude.formatDecimals(7))
                coordTable.addCell(v.longitude.formatDecimals(7))
                coordTable.addCell(v.altitude.formatDecimals(2))
            }
            document.add(coordTable)
        } finally {
            document.close()
        }
        return file
    }
}
